apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-Deployment
  labels:
    app: mongodb
    tier: database
  namespace: kube-notbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      tier: database
  template:
    metadata:
      labels:
        app: mongodb
        tier: database
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: notebook-Secrets
                  key: mongo-dbusername
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notebook-Secrets
                  key: mongo-dbpassword
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: notebook-Secrets
                  key: mongo-uri
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-Service
  labels:
    app: notebook
    tier: database
  namespace: kube-notebook
spec:
  selector:
    app: notebook
  ports:
    - port: 27017
      targetPort: 27017