apiVersion: v1
kind: Secrets
metadata:
  name: notebook-Secrets
  labels:
    app: notebook
type: opaque
data:
  mongo-dbusername: XNlcm5hbWU=
  mongo-dbpassword: cGFzc3dvcmQ=
  jwt_secret: dGhpc2lzdGhlbW9zdHNlY3VyZXNlcnZlcg==
  mongo-uri: mongo-Service
  mongo-db-init: notebookdb